# Generated by Django 4.1.3 on 2022-12-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="stu_branch",
            field=models.CharField(default="cse", max_length=10),
        ),
    ]
